input {
  http {
    host => "0.0.0.0"
    port => 8081
    ecs_compatibility => disabled
    response_code => 200
  }
}

filter {
  mutate {
    add_field => { "ingest_component" => "logstash" }
  }

  if [headers] {
    mutate {
      remove_field => [ "headers" ]
    }
  }
}

output {
  elasticsearch {
    hosts => [ "http://elasticsearch:9200" ]
    index => "smart-slice-predictions"
  }

  stdout {
    codec => rubydebug
  }
}
