#!/bin/sh
set -eu

# This script must keep LF line endings so the Postgres entrypoint can execute it on Windows bind mounts.
: "${POSTGRES_USER:?POSTGRES_USER must be set}"

DASHBOARD_DB_NAME="${DASHBOARD_POSTGRES_DB:-neuroslice_dashboard}"
AUTH_ROLE="${AUTH_DB_USER:-auth_app}"
AUTH_ROLE_PASSWORD="${AUTH_DB_PASSWORD:-auth_pass}"
DASHBOARD_ROLE="${DASHBOARD_DB_USER:-dashboard_app}"
DASHBOARD_ROLE_PASSWORD="${DASHBOARD_DB_PASSWORD:-dashboard_pass}"

if [ -z "${AUTH_ROLE_PASSWORD}" ]; then
  echo "AUTH_DB_PASSWORD must not be empty." >&2
  exit 1
fi

if [ -z "${DASHBOARD_ROLE_PASSWORD}" ]; then
  echo "DASHBOARD_DB_PASSWORD must not be empty." >&2
  exit 1
fi

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<SQL
DO
\$do\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${AUTH_ROLE}') THEN
        EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', '${AUTH_ROLE}', '${AUTH_ROLE_PASSWORD}');
    ELSE
        EXECUTE format('ALTER ROLE %I LOGIN PASSWORD %L', '${AUTH_ROLE}', '${AUTH_ROLE_PASSWORD}');
    END IF;

    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${DASHBOARD_ROLE}') THEN
        EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', '${DASHBOARD_ROLE}', '${DASHBOARD_ROLE_PASSWORD}');
    ELSE
        EXECUTE format('ALTER ROLE %I LOGIN PASSWORD %L', '${DASHBOARD_ROLE}', '${DASHBOARD_ROLE_PASSWORD}');
    END IF;
END
\$do\$;
SQL

if [ "$(psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres -tAc "SELECT 1 FROM pg_database WHERE datname='${DASHBOARD_DB_NAME}'")" != "1" ]; then
  psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres \
    -c "CREATE DATABASE \"${DASHBOARD_DB_NAME}\" OWNER \"${DASHBOARD_ROLE}\""
fi

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<SQL
ALTER DATABASE "${DASHBOARD_DB_NAME}" OWNER TO "${DASHBOARD_ROLE}";
GRANT CONNECT ON DATABASE "${DASHBOARD_DB_NAME}" TO "${AUTH_ROLE}";
GRANT CONNECT ON DATABASE "${DASHBOARD_DB_NAME}" TO "${DASHBOARD_ROLE}";
GRANT TEMP, CREATE ON DATABASE "${DASHBOARD_DB_NAME}" TO "${AUTH_ROLE}";
GRANT TEMP, CREATE ON DATABASE "${DASHBOARD_DB_NAME}" TO "${DASHBOARD_ROLE}";
SQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$DASHBOARD_DB_NAME" <<SQL
CREATE SCHEMA IF NOT EXISTS auth AUTHORIZATION "${AUTH_ROLE}";
CREATE SCHEMA IF NOT EXISTS dashboard AUTHORIZATION "${DASHBOARD_ROLE}";

ALTER SCHEMA auth OWNER TO "${AUTH_ROLE}";
ALTER SCHEMA dashboard OWNER TO "${DASHBOARD_ROLE}";

GRANT USAGE ON SCHEMA auth TO "${DASHBOARD_ROLE}";
GRANT USAGE, CREATE ON SCHEMA auth TO "${AUTH_ROLE}";
GRANT USAGE, CREATE ON SCHEMA dashboard TO "${DASHBOARD_ROLE}";
GRANT SELECT, REFERENCES ON ALL TABLES IN SCHEMA auth TO "${DASHBOARD_ROLE}";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA auth TO "${DASHBOARD_ROLE}";

ALTER DEFAULT PRIVILEGES FOR ROLE "${AUTH_ROLE}" IN SCHEMA auth
GRANT SELECT, REFERENCES ON TABLES TO "${DASHBOARD_ROLE}";

ALTER DEFAULT PRIVILEGES FOR ROLE "${AUTH_ROLE}" IN SCHEMA auth
GRANT USAGE, SELECT ON SEQUENCES TO "${DASHBOARD_ROLE}";
SQL
