#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
DO
\$do\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${AUTH_DB_USER}') THEN
        EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', '${AUTH_DB_USER}', '${AUTH_DB_PASSWORD}');
    END IF;

    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${DASHBOARD_DB_USER}') THEN
        EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', '${DASHBOARD_DB_USER}', '${DASHBOARD_DB_PASSWORD}');
    END IF;
END
\$do\$;

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${AUTH_DB_USER};
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${DASHBOARD_DB_USER};
GRANT CREATE ON DATABASE ${POSTGRES_DB} TO ${AUTH_DB_USER};
GRANT CREATE ON DATABASE ${POSTGRES_DB} TO ${DASHBOARD_DB_USER};

CREATE SCHEMA IF NOT EXISTS auth AUTHORIZATION ${AUTH_DB_USER};
CREATE SCHEMA IF NOT EXISTS dashboard AUTHORIZATION ${DASHBOARD_DB_USER};

GRANT USAGE ON SCHEMA auth TO ${DASHBOARD_DB_USER};
GRANT USAGE ON SCHEMA dashboard TO ${DASHBOARD_DB_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE ${AUTH_DB_USER} IN SCHEMA auth
GRANT SELECT, REFERENCES ON TABLES TO ${DASHBOARD_DB_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE ${AUTH_DB_USER} IN SCHEMA auth
GRANT USAGE, SELECT ON SEQUENCES TO ${DASHBOARD_DB_USER};
SQL
